name: GetProduct_build_test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.Shopify.GetProduct/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.Shopify.GetProduct
      dotnet_version: 8.0.x
      env_var_name_1: FRENDS_ShopifyTest_accessToken
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
